In [85]:
import pandas as pd
from yt_dlp import YoutubeDL
from bs4 import BeautifulSoup
import ffmpeg

In [86]:
df = pd.read_csv('eval_segments_reg.csv', quotechar="'")
df

,# YTID,start_seconds,end_seconds,positive_labels
0,--BfvyPmVMo,20.0,30.0,"""/m/03l9g"""
1,--U7joUcTCo,0.0,10.0,"""/m/01b_21"""
2,--i-y1v8Hy8,0.0,9.0,"""/m/04rlf;/m/09x0r;/t/dd00004;/t/dd00005"""
3,-0BIyqJj9ZU,30.0,40.0,"""/m/07rgt08;/m/07sq110;/t/dd00001"""
4,-0CamVQdP_Y,0.0,6.0,"""/m/04rlf;/m/07pbtc8;/m/09x0r"""
...,...,...,...,...
20365,zyF8TGSRvns,150.0,160.0,"""/m/0dwsp;/m/0dwtp;/m/0f8s22;/m/0j45pbj"""
20366,zz35Va7tYmA,30.0,40.0,"""/m/012f08;/m/07q2z82;/m/07qmpdm;/m/0k4j"""
20367,zzD_oVgzKMc,30.0,40.0,"""/m/07pn_8q"""
20368,zzNdwF40ID8,70.0,80.0,"""/m/04rlf;/m/0790c"""
20369,zzbTaK7CXJY,30.0,40.0,"""/m/03m9d0z;/m/07qwyj0;/t/dd00092"""

In [87]:
df

,# YTID,start_seconds,end_seconds,positive_labels
0,--BfvyPmVMo,20.0,30.0,"""/m/03l9g"""
1,--U7joUcTCo,0.0,10.0,"""/m/01b_21"""
2,--i-y1v8Hy8,0.0,9.0,"""/m/04rlf;/m/09x0r;/t/dd00004;/t/dd00005"""
3,-0BIyqJj9ZU,30.0,40.0,"""/m/07rgt08;/m/07sq110;/t/dd00001"""
4,-0CamVQdP_Y,0.0,6.0,"""/m/04rlf;/m/07pbtc8;/m/09x0r"""
...,...,...,...,...
20365,zyF8TGSRvns,150.0,160.0,"""/m/0dwsp;/m/0dwtp;/m/0f8s22;/m/0j45pbj"""
20366,zz35Va7tYmA,30.0,40.0,"""/m/012f08;/m/07q2z82;/m/07qmpdm;/m/0k4j"""
20367,zzD_oVgzKMc,30.0,40.0,"""/m/07pn_8q"""
20368,zzNdwF40ID8,70.0,80.0,"""/m/04rlf;/m/0790c"""
20369,zzbTaK7CXJY,30.0,40.0,"""/m/03m9d0z;/m/07qwyj0;/t/dd00092"""

In [88]:
#get url from ID

prefix = "https://www.youtube.com/watch?v="

#test on row 2
row_two = df.iloc[[2]]

#get YT id
id = row_two['# YTID']

url = prefix + id

In [89]:
# Taken from https://www.scraperapi.com/blog/how-to-scrape-youtube/
## Downloading a YouTube Video
def download_video(video_url):
    opts = {}
    with YoutubeDL(opts) as yt:
        yt.download(video_url)
    print(f"Downloaded video: {video_url}")

download_video(url)

[youtube] Extracting URL: https://www.youtube.com/watch?v=--i-y1v8Hy8
[youtube] --i-y1v8Hy8: Downloading webpage
[youtube] --i-y1v8Hy8: Downloading ios player API JSON
[youtube] --i-y1v8Hy8: Downloading web creator player API JSON
[youtube] --i-y1v8Hy8: Downloading player 96d06116
[youtube] --i-y1v8Hy8: Downloading m3u8 information

WARNING: ffmpeg not found. The downloaded format may not be the best available. Installing ffmpeg is strongly recommended: https://github.com/yt-dlp/yt-dlp#dependencies

[info] --i-y1v8Hy8: Downloading 1 format(s): 18
[download] Destination: Mackenzie ziegler singing  drunk in love rare [--i-y1v8Hy8].mp4
[download] 100% of  382.25KiB in 00:00:00 at 2.30MiB/s
Downloaded video: 2    https://www.youtube.com/watch?v=--i-y1v8Hy8
Name: # YTID, dtype: object